variable "region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-2"
}

variable "name_prefix" {
  description = "Prefix applied to all resource names"
  type        = string
  default     = "msr"
}

variable "instance_type" {
  description = "EC2 instance type for the single-node k0s cluster running MSR"
  type        = string
  default     = "t3.xlarge" # 4 vCPU / 16 GiB
}

variable "root_volume_gb" {
  description = "Root EBS volume size in GiB (holds k0s, images, and MSR persistent volumes)"
  type        = number
  default     = 100
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key used for the EC2 key pair (generated by deploy.sh, never committed)"
  type        = string
}

variable "allowed_cidr" {
  description = "CIDR allowed to reach SSH and the MSR UI. Empty string = auto-detect the deployer's public IP."
  type        = string
  default     = ""
}

variable "msr_https_nodeport" {
  description = "NodePort exposing MSR HTTPS (UI + registry API); matches the MSR chart default"
  type        = number
  default     = 30003
}

variable "k0s_version" {
  description = "k0s version to install on the node (Kubernetes 1.31-1.32 per the MSR 4.13 compatibility matrix)"
  type        = string
  default     = "v1.32.13+k0s.0"
}
